"""αρχικό σχήμα: users, lines, stops, reports, confirmations

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-28 18:31:29.832288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.Enum('BUS', 'TROLLEY', 'METRO', 'TRAM', 'SUBURBAN', name='transportmode', native_enum=False, length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lines_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PASSENGER', 'OPERATOR', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmations_received', sa.Integer(), nullable=False),
    sa.Column('disputes_received', sa.Integer(), nullable=False),
    sa.CheckConstraint('confirmations_received >= 0', name='ck_users_confirmations_non_negative'),
    sa.CheckConstraint('disputes_received >= 0', name='ck_users_disputes_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_stops_position_non_negative'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'position', name='uq_stops_line_position')
    )
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stops_line_id'), ['line_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('delay_minutes', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('DELAY', 'NO_SHOW', 'OVERCROWDED', name='reportcategory', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('delay_minutes >= -30.0 AND delay_minutes <= 180.0', name='ck_reports_delay_within_bounds'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_line_id'), ['line_id'], unique=False)

    op.create_table('confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agrees', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', name='uq_confirmations_report_user')
    )
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confirmations_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confirmations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confirmations_user_id'))
        batch_op.drop_index(batch_op.f('ix_confirmations_report_id'))

    op.drop_table('confirmations')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_line_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_reports_author_id'))

    op.drop_table('reports')
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_line_id'))

    op.drop_table('stops')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lines_code'))

    op.drop_table('lines')
    # ### end Alembic commands ###
